### PR TITLE
Update call_flow.lua

### PR DESCRIPTION
**Pull request by JoinFreeMe**
Allows to use an 'action' > 'set' > call_flow_sound_on=/{path_to_audio_file.wav}  and  call_flow_sound_off=/{path_to_new_audio_file.wav} in the dialplan of a call flow so that after a feature code has been dialled and the password has been entered a recording is played dependant upon the status of that call flow.

Example: (feature code *281 for call flow)
turn on call flow *281 > 1234# > my .wav file is played     "CALLS TO DIVERT"
turn off call flow *281 > 1234# > my .wav file is played     "CALLS TO OFFICE"

dial - enter password - status of call flow changes - recording plays dependant on true or false

### CODE REVIEW

**Comment by moteus** [comment]
Looks familier :).
But really it is not ideal solution because call flow dialplan extension recreates each time you save it in Web interface so you have to add one more extension in dialplan or edit it each time.
Correct solution is add this fields to DB.

**Comment by JoinFreeMe** [comment]
Working on the Web interface

**Comment by moteus** [comment]
I mean when you save it in `App->Call Flow->Edit->Save` Fusion recreates extension in dialplan manager and it remove all changes you create in it.

**Comment by JoinFreeMe** [comment]
I'll have a poke around, may request some help if that's alright?

**Pull request closed without merging**
