### PR TITLE
Bugfix-conference center rooms

### PR DESCRIPTION
**Pull request by mafoo**
Fix for when a conference room has no admins

If a conference room had no admins it would become impossible to see it
in the GUI
This fix makes it possible for a admin or super admin to view rooms in
this state.
- [x] convert to use permission "conference_room_view_all"

### CODE REVIEW

**Comment by daniel-lucio** [comment]
instead of doing if (if_group("admin") or if_group("superadmin")) {, check if there is a grou permision, that is the correct way

**Comment by markjcrane** [comment]
He is correct permission is the correct way and if_group("admin") and if_group("superadmin") are to be rarely in favor of permissions.

**Comment by mafoo** [comment]
added permission conference_room_view_all, I will bare in mind when adjust existing code that is using is_group to convert it at the same time over to permission instead

**Comment by markjcrane** [comment]
Please rebuild the pull request with the new conference_room_view_all permissions.

**Pull request closed without merging**
