### PR TITLE
Update 400_recordings.xml

### PR DESCRIPTION
**Pull request by mtghr**
the system didnt ask me for the ID

### CODE REVIEW

**Comment by markjcrane** [comment]
I made this code and changed it intentionally to use recording id instead of recording slots this was not an accident.

**Comment by mtghr** [comment]
ok,

now i see that the reason it didnt work is cause recording_id was = true i need it to remove "true"

**Comment by mtghr** [comment]
i am just wondering where that "true" came from 
is there any other place that will change this code from the dial plan?

**Comment by markjcrane** [comment]
The true was an old value. That was there since the dialplan was created.

**Pull request closed without merging**
