### PR TITLE
TFTP Service 1.0.7

### PR DESCRIPTION
**Pull request by minotaur01**
Fixed linux and windows run as service issues
Fixed linux systemd service self install issues
Modified windows service self install process

### CODE REVIEW

**Comment by minotaur01** [comment]
mcrane, so it seems branching makes no difference in the pull request showing all the commits i have ever done! :( I will figure this out!

**Comment by markjcrane** [comment]
I really want a clean commit. If you start over with a new git hub directory this would not happen.

**Comment by markjcrane** [comment]
See if you can update this tonight if you want it in the release.

**Comment by minotaur01** [comment]
Okay, I'm working on a clean pull request right now.

**Pull request closed without merging**
