### PR TITLE
Update follow_me.php

### PR DESCRIPTION
**Pull request by skyeblueiscool**
Fix issue #1434

Follow Me Prefix breaks CID

### CODE REVIEW

**Comment by markjcrane** [comment]
Follow instructions here so that we can accept your pull request.
https://github.com/fusionpbx/open-source

**Comment by skyeblueiscool** [comment]
Done

**Comment by markjcrane** [comment]
I don't see your pull request on the fusionpbx  open source repository.

**Comment by skyeblueiscool** [comment]
Okay - Done.

**Comment by markjcrane** [comment]
If you succeed I would see it here. https://github.com/fusionpbx/open-source/pulls your goal is to add yourself to the contributors list like these people did https://github.com/fusionpbx/open-source/tree/master/contributors.

**Comment by skyeblueiscool** [comment]
Okay, I think its there now.

**Comment by markjcrane** [comment]
You got it.

**Pull request merged**
