### PR TITLE
Add customization for email

### PR DESCRIPTION
**Pull request by ewyand**
Give the ability to customize the smtp from domain and name for voicemail and fax separately

### CODE REVIEW

**Comment by markjcrane** [comment]
It looks like a good change. Missing an app_defaults.php that changes email to voicemail for the default settings. Otherwise anyone that upgrades will be broken unless they know about this change.

**Comment by markjcrane** [comment]
So that needs to be completed.

**Comment by ewyand** [comment]
Where would the app_default.php go? Sorry for the dumb question. I do not code. I can semi-read it and figure out what is going on.
I was able to add the smtp_from and smtp_from_name under the respective category ie Fax and Voicemail and it worked for me. I was also able to copy it to the domain and the domain setting took priority.

**Comment by ewyand** [comment]
Will these changes work?

**Pull request merged**
