### PR TITLE
Fix IVR when using custom recordings

### PR DESCRIPTION
**Pull request by daniel-lucio**
Same rationale as 4.2

### CODE REVIEW

**Comment by markjcrane** [comment]
It uses relative path directories on purpose this would hard code the paths.

**Comment by daniel-lucio** [comment]
Lets keep conversation in this post.

I know it is a relative path, but there are 2 issues that are not meeting here.
if relative path, sound is looked in the sounds_dir directory, aka /usr/share/freeswitch/sounds/. Custom recordings are not there.

custom recordings (the ones that are available at app->recording) path should be absolute as usually it is  recording_dir/domain/something, for example /var/lib/freeswitch/recordings/mydomain/file.wav

The patch only uses absolute paths when using custom recordings, not in another place.

**Comment by markjcrane** [comment]
We look in sounds and custom recordings for the relative path.

**Comment by daniel-lucio** [comment]
Where is that part the code that looks when relative path, I couldn't find not in the PHP not in the LUA. This is the reason of this patch.

**Comment by markjcrane** [comment]
4.2 uses xml handler by default but also the option for to use ivr_menu.lua. Both of the files have relative path searching to fix the set the full path. You should probably explain state which one you are using.

**Comment by markjcrane** [comment]
Relative path is more flexible allow the base path to be changed without having update the path on all of the IVR Menus.

**Pull request closed without merging**
