### PR TITLE
Finished pt-BR Translations

### PR DESCRIPTION
**Pull request by fneto1977**

### CODE REVIEW

**Comment by fneto1977** [comment]
Hi! It's my first time using git, and I don't know if I have made some mistake, so please, if I have made something that I shouldn't please explain to me and I will fix it. 
I hope my fixed translations can help the community as a whole! 
Thanks!

**Comment by markjcrane** [comment]
Make a copy of the directory then try using a git rebase to update the pull request. App/edit has been moved to its own repo.

**Comment by fneto1977** [comment]
> Make a copy of the directory then try using a git rebase to update the pull request. App/edit has been moved to its own repo.

Hi Mark It's my first time using git, so if you could be more didactic with me or explain in a step by step I will be very glad, because the last thing I want do is a mess in the repository, and I've read some information about the rebase and I really get scared !

So how can I make a copy of the directory? Which directory and where? on git on in the local machine?

Where should I run the git-rebase and after the pull request?

By the last, I didn't understand about the app/edit, it was moved to the root??

**Comment by markjcrane** [comment]
Please put in a ticket at www.fusionpbx.com. Will use that as a point of contact.

**Comment by fneto1977** [comment]
> Please put in a ticket at [www.fusionpbx.com](http://www.fusionpbx.com). Will use that as a point of contact.

I've already opened a ticket there on 12-08-2019 with the title "Finished pt-BR Translations #4926"

Now I'm waiting for your instructions to finish the translation ok!

**Comment by markjcrane** [comment]
Closing pull requests that Shows 5000+ changes. Please resubmit with code on latest master.

**Pull request closed without merging**
