### PR TITLE
Enhance [master] add column descriptions to xml_cdr

### PR DESCRIPTION
**Pull request by mafoo**
update th_order_by to accept optional description parameter that will
populate the title field and append the , sort(order)

### CODE REVIEW

**Comment by markjcrane** [comment]
Need to make this multi-lingual capable. We don't want to add in hard coded 'English'.

**Comment by mafoo** [comment]
I have done a rebase and squash, included translations where practical

**Comment by markjcrane** [comment]
The organize languages pull request just conflicted with this one.

**Comment by mafoo** [comment]
reworked the PR to merge cleanly

**Pull request merged**
