### PR TITLE
Localization: Add full support for Georgian language

### PR DESCRIPTION
**Pull request by NorwayFun**
Hello,
Here's full translation of FusionPBX to Georgian language.
We've translated everything we could find.
In case of any questions, please let me know.

Temuri

### CODE REVIEW

**Comment by NorwayFun** [comment]
// CLA signed

**Comment by markjcrane** [comment]
I just checked and I don't see the contributor license agreement pull request here.
- https://github.com/fusionpbx/open-source

When that is done I'll accept your pull request.

**Comment by NorwayFun** [comment]
Sorry for that, did it before coffee :)
Is there now.

**Comment by NorwayFun** [comment]
Thanks!
I see many correctons coming soon :)
Just one question, please.
When I tried to install FusionPBX by replacing repo name in respecing file, it did install (debian12), but most of entry interface (e.g. "Home" are still in English. Any suggeions?

**Comment by etgcloudvoicesupport** [comment]
Are you changing it in the default, domain, or user settings? Changing the repo name/editing files shouldn't impact what language is used in the interface, that is all dependent upon the settings
https://docs.fusionpbx.com/en/latest/getting_started/languages.html

Another thing to note is that there are various interactive voice prompts, such as the voicemail, that I don't think will be localized, so far this only gets the fusionpbx GUI elements. It sounds like you started this out with AI to translate, an idea to get an initial version of the voice prompts is to go a similar route but to generate the voice prompt wav files.
https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Installation/Language-Files_13174130/
Fusionpbx uses the prompts from freeswitch for voice prompts.

**Comment by demonspork** [comment]
Are you changing it in the default, domain, or user settings? Changing the repo name/editing files shouldn't impact what language is used in the interface, that is all dependent upon the settings
https://docs.fusionpbx.com/en/latest/getting_started/languages.html

Another thing to note is that there are various interactive voice prompts, such as the voicemail, that I don't think will be localized, so far this only gets the fusionpbx GUI elements. It sounds like you started this out with AI to translate, an idea to get an initial version of the voice prompts is to go a similar route but to generate the voice prompt wav files.
https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Installation/Language-Files_13174130/
Fusionpbx uses the prompts from freeswitch for voice prompts.

**Comment by markjcrane** [comment]
Unfortunately, your files weren't completed up to date. I'm working on fixing the files.
The next problem you didn't realize the languages are alphabetically ordered and put it right after English rather than the right order.

**Comment by NorwayFun** [comment]
I pulled latest repo and did changes on it. Was I wrong?
Also, that is, why I put it after it-it. Since Georgian language code is "ka-ge" it should go after it-it, shouldn't it?
Please, let me know which part is left without translations and I'll do it.
Anyways, thanks for help

**Comment by markjcrane** [comment]
Run this command and report which branch you are on.

cd /var/www/fusionpbx
git branch

**Comment by markjcrane** [comment]
I've repaired resources/app_languages.php the main shared translation file.

**Comment by NorwayFun** [comment]
It's master, I've changed config.sh :)
Should I reinstall FreePBX for changes to appear? I saw some localized strings in DB too..

**Comment by markjcrane** [comment]
You can look at the file changes on this pull request.
- This one had a lot missing but is fixed resources/app_languages (fixed)
- Looks like /var/www/fusionpbx/core/*/app_languages.php were the language that was added was in the right location in alphabetical order this is good news.
- Missing changes in
  - core/user_settings/app_languages.php missing some translations and tr-tr
- Still need to look at every file that was change in the /var/www/fusionpbx/app/*/app_languages.php files. To see what is wrong in them.

**Comment by markjcrane** [comment]
Problems aren't as extensive as I had thought they might be when I worked on resources/app_languages.php shared file.

**Comment by NorwayFun** [comment]
Translating remaining strings right now :)

**Comment by markjcrane** [comment]
I'm working on core/user_settings/app_languages.php

**Comment by markjcrane** [comment]
There is a new pull request for changes to the translations. Here is a link to that pull request can you please review the changes.
https://github.com/fusionpbx/fusionpbx/pull/7113

**Pull request merged**
