### PR TITLE
4.0

### PR DESCRIPTION
**Pull request by idfbobby**

### CODE REVIEW

**Comment by mafoo** [comment]
i have reworked this as a cherry picked commit see - https://github.com/fusionpbx/fusionpbx/pull/1355

**Comment by markjcrane** [comment]
To get commits accepted follow instructions here.
https://github.com/fusionpbx/open-source

**Comment by idfbobby** [comment]
I have followed the directions and signed the agreement. What the
instructions don't say is how I send changes to you all. Sorry, not trying
to be a pest, just not sure how it works.

**Comment by markjcrane** [comment]
idfbobby: sorry I noticed you had signed the agreement so I deleted my comment. Your help is appreciated if you notice other bug fixes to push to 4.0 feel free to add a new pull request.

**Pull request closed without merging**
