### PR TITLE
Fix. Remove duplicate options from internal profile.

### PR DESCRIPTION
**Pull request by moteus**

### CODE REVIEW

**Comment by markjcrane** [comment]
Are these duplicates? I know they are settings that could be a disruptive if not disabled.

**Comment by moteus** [comment]
They appear twice on web.
Same as caller-id-type. But it has different values so you can enable one value so it may be useful.

**Comment by moteus** [comment]
screenshot_1

**Comment by markjcrane** [comment]
New duplicates should be handled. I can see these are dangerous settings so I will comment them out instead of deleting them. Here is the reference to the commit 8909639101366f9ea43a717235a14eec90573205

**Pull request closed without merging**
