### PR TITLE
faxing smtp_port fix + smtp certificate override

### PR DESCRIPTION
**Pull request by jebsolutions**
smtp_ignore_bad_certificate is added to default settings.  Default is false.

If set to true then will add flags for PHPMailer to ignore certificate checks.  This lets you use self-signed certificates.

Note: you have a similar override as an option for imap on the fax server advanced options.  This patch does something the equivalent on the SMTP side for sending fax and voicemail to email.

This patch lets you use self-signed certs on recent php/phpmailer combinations.  

This patch lets fax-to-email work with non-standard smtp ports by adding similar logic from voicemail-to-email (v_mailto.php).

### CODE REVIEW

**Comment by markjcrane** [comment]
I don't like smtp_ignore_bad_certificate as a self signed certificate is a valid certificate.  smtp_validate_certificate or smtp_allow_self_signed maybe a better choice for the name.
Please update this and fix the conflicts or submit a new pull request.

**Comment by jebsolutions** [comment]
@markjcrane,

Thanks for the feedback.  I will change to use smtp_validate_certificate.

Will look at the conflicts.

**Comment by markjcrane** [comment]
branch still conflicting.

**Comment by jebsolutions** [comment]
I am closing this PR since it's obsoleted by my other PRs.

**Pull request closed without merging**
