### PR TITLE
[4.5] DTMF handling

### PR DESCRIPTION
**Pull request by daniel-lucio**
this will give the dtmf_history (similar to the transfer_history variable)

the use cases of this are only limited to the imagination

### CODE REVIEW

**Comment by winsock** [comment]
Couldn't this be simplified by using the DTMF event and the `DTMF-Digit` header?

```lua
local call_uuid = event:getHeader("Caller-Unique-ID");
local channel_timestamp = event:getHeader("Event-Date-Timestamp");
local dtmf_value = event:getHeader("DTMF-Digit");

local session = freeswitch.Session(call_uuid);
local history = channel_timestamp .. ':' .. dtmf_value .. "\n";
session:execute("push", "dtmf_history="..history);

-- lua.conf.xml
-- <hook event="DTMF" script="dtmf_handler.lua"/>
```

**Comment by daniel-lucio** [comment]
odd, when I first did an event="all" to find out what's the event name that was being fired, my FreeSwitch only showed RECV_INFO not DTMF, I am fixing it as per your suggestion

**Comment by winsock** [comment]
Not sure why it didn't show for you originally, but I am using the DTMF event in my ESL application/library without issue.

**Comment by emaktech** [comment]
Super useful PR, I can see this being useful to help us capture DTMF events and use them for later logging and analysis!

**Pull request merged**
