### PR TITLE
Fixed gxp2170 template value register_timeout 

### PR DESCRIPTION
**Pull request by kusznir**
Somehow this was static'ed to 60 minutes.  Set with variable so it pulls from device settings now.

### CODE REVIEW

**Comment by kusznir** [comment]
Also fix pc passthrough vlan default back to sane value

**Comment by digitalcrisis** [comment]
This does need to be fixed, it caused a lot of headaches.

**Comment by kusznir** [comment]
Fixed more bugs in the templates.

**Comment by markjcrane** [comment]
Some of the changes look good some not so good so a live conversation over a call would be best.

**Pull request merged**
