### PR TITLE
Bugfix root php logic

### PR DESCRIPTION
**Pull request by mafoo**
more universal fix for - https://github.com/fusionpbx/fusionpbx/issues/1297
 and https://github.com/fusionpbx/fusionpbx/pull/1328
- [x] in root.php address PROJECT_PATH detection more reliably
- [x] in root.php provide $_SERVER['PROJECT_ROOT']
- [x] Feedback from mark on if this is a suitable
- [x] rollout root.php
- [x] update upgrade to use $_SERVER['PROJECT_ROOT'] instead
- [x] Test new search mechanism

### CODE REVIEW

**Comment by vindicatorr** [comment]
Just an FYI, from IRC
```
You're right mcrane, commit 76b1ea734e62c9886210abf945e9df4de31b3fe5 is where it breaks. The preceding 74ca9eb980b45116d5a3c652adf36ff36360d24c comes up with the install_first_time just fine.
```
Referring to "/core/install/install_first_time.php"
```
FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(resources/functions.php): failed to open stream: No such file or directory in /.../fusionpbx/core/install/install_first_time.php on line 28
```

**Comment by markjcrane** [comment]
Adding that you said this is on arch Linux
Please share the full path to the fusionpbx directory.

**Comment by vindicatorr** [comment]
Archlinux (ARM)
PHP 5.6.16
fullpath: /home/web/fusionpbx
chown: http
find -type f chmod 644
find -type f chmod 755

**Comment by mafoo** [comment]
not copying .project.ROOT caused this problem

**Pull request merged**
