### PR TITLE
Change. Use `require "resources.functions.config"` to load config file.

### PR DESCRIPTION
**Pull request by moteus**
Change. Move `script_dir` definition into config file.

This allows load config file only once.
It this ok then I also change all dofile that load modules such as database_handler/file_exists.

### CODE REVIEW

**Comment by markjcrane** [comment]
Reverted - My system couldn't follow the path and so it broke everything.

**Comment by moteus** [comment]
Did you set `<param name="script-directory" value="$${base_dir}/scripts/?.lua"/>` in `lua.conf.xml`?

**Comment by markjcrane** [comment]
But I likely  forgot to restart freeswitch. Your note should have gone in the commit message as this will break every system that upgrades until making that change and restarting.

What is the benefit to the change? It looks prettier than dofile but is there a performance gain?

**Comment by moteus** [comment]
`dofile` load file each time but `require` load file only once. This is why I left handlers with dofile.
Also with `require` you can load other libraries (e.g. installed via LuaRocks) and code will be same.

**Comment by markjcrane** [comment]
Tested again and it worked if you resubmit the pull request I will apply it.

**Pull request merged**
