### PR TITLE
Update y000000000028.cfg

### PR DESCRIPTION
**Pull request by StevCero**
Add variables for Intercom Mute and Voicemail Tone

### CODE REVIEW

**Comment by markjcrane** [comment]
Please sign up as a contributor here and we will accept your changes.
https://github.com/fusionpbx/open-source

**Comment by StevCero** [comment]
I should already be signed up as a contributor.

**Comment by markjcrane** [comment]
I just looked again and I don't see username StevCero in https://github.com/fusionpbx/open-source/tree/master/contributors and didn't find it in pull requests either for that repo.

**Comment by markjcrane** [comment]
This pull request cannot be merged because of a former change in the code. If you would like to add your change then please add the changes to the new version of FusionPBX and add a new pull request. Sorry about this problem.

**Pull request closed without merging**
