### PR TITLE
fix Russian translation error

### PR DESCRIPTION
**Pull request by Pro-pra**

### CODE REVIEW

**Comment by markjcrane** [comment]
Please sign up as a contributor. You can find instructions at the link below.
https://github.com/fusionpbx/open-source

You send a pull request to 
https://github.com/fusionpbx/open-source/contributors.

**Comment by Pro-pra** [comment]
CLA mail sent

signed.

**Comment by markjcrane** [comment]
I don't see your pull request for this if you go to that url you will see other contributors have their github username.md. In your case it would be Pro-pra.md
https://github.com/fusionpbx/open-source/tree/master/contributors

**Comment by Pro-pra** [comment]
fixed.

**Pull request merged**
