### PR TITLE
Add. Support sound prompts on call flow.

### PR DESCRIPTION
**Pull request by moteus**
This file uses new way to load recordings from DB.

This is replace to #1642 and #1640

### CODE REVIEW

**Comment by blackc2004** [comment]
I'm not sure how this PR replaced 1644 at all? My PR1644 is to enable the *411 directory to speak the name instead of just spelling it out using the mod_flite or mod_cepstral.

**Comment by moteus** [comment]
>I'm not sure how this PR replaced 1644 at all? 

Sorry fixed.

**Comment by markjcrane** [comment]
moteus  github user JoinFreeMe hasn't followed the instructions in fusionpbx/open-source yet so if you used any of his source code then I can't accept this PR until he does.

**Comment by JoinFreeMe** [comment]
Tested - Debian (working)

**Pull request merged**
