### PR TITLE
Change. Use number_alias as voicemail_id.

### PR DESCRIPTION
**Pull request by moteus**
In my system we use numeric auth id and short number alias.
May be also needed update `extension-to-voicemail` extension.

### CODE REVIEW

**Comment by richbreton** [comment]
Please view the link below to see our process:

https://github.com/fusionpbx/open-source/blob/master/sign-cla.md

**Comment by markjcrane** [comment]
Can you update the pull request as it currently has conflicts.

**Comment by markjcrane** [comment]
Can you update the pull request as it currently has conflicts.

**Comment by moteus** [comment]
update

**Pull request merged**
