### PR TITLE
Fix cdr delete for recordings schema change and minor refactoring

### PR DESCRIPTION
**Pull request by demonspork**
Minor refactoring of the delete method for readability and fixing it for the new recordings view.

### CODE REVIEW

**Comment by bigsys-it** [comment]
Hi!

Can you approve this fix?

**Comment by markjcrane** [comment]
It looks like we might loose changes from other people's commits.

**Comment by demonspork** [comment]
Which part is that? I have another PR that I think does have that issue, I changed its name to WIP until I have time to refactor it but I believe this one was clean.

**Comment by markjcrane** [comment]
This commit would get removed.
https://github.com/fusionpbx/fusionpbx/commit/a3811128af2ed4ae33552d684037aa2916f2520a

**Comment by markjcrane** [comment]
Looks like it also wipes this one out.
https://github.com/fusionpbx/fusionpbx/commit/9aa88dc5370b6a42283a2a6d8d9b49f1ced9315e

**Comment by markjcrane** [comment]
I went through this with a program called meld
- https://meldmerge.org/

**Pull request merged**
