### PR TITLE
Update provision.php

### PR DESCRIPTION
**Pull request by PBXForums**
Make a key available in the template for whitelisting.

### CODE REVIEW

**Comment by markjcrane** [comment]
Why could this not be done with a device setting?

**Comment by markjcrane** [comment]
I have lots of concerns with this pull request.

**Comment by DigiDaz** [comment]
Yes, its a calculated value.

**Comment by markjcrane** [comment]
I think there is a likely a better name for the variable. Will try to find some time come up with a name.

**Comment by markjcrane** [comment]
Closing pull request if still interested in adding changes update them and submit a new pull request.

**Pull request closed without merging**
