### PR TITLE
Update device_copy.php

### PR DESCRIPTION
**Pull request by goldenpr**
MAC Address Duplication Issue

### CODE REVIEW

**Comment by markjcrane** [comment]
Please sign up as a contributor here and your pull request will be accepted.
- https://github.com/fusionpbx/open-source

**Comment by goldenpr** [comment]
Done

**Comment by demonspork** [comment]
Did you notice that all of your edits are being pushed to this PR? Just an FYI.

The way to avoid this in future PRs is to create a new branch with the edit you want, make the PR, and then you can edit other branches or even your master branch and not impact the commits that are included in the PR.

**Comment by goldenpr** [comment]
Sorry I'm new in GitHub, I don't know what do you mean by PR and I don't want them to marge all my commits. I'm just customizing my own version of Fusion PBX. 

Best Regards.

**Pull request closed without merging**
