### PR TITLE
add Diversion Header to dail string

### PR DESCRIPTION
**Pull request by de-jens**
When a call gets forwarded you will see form witch Extension it came from.

https://tools.ietf.org/html/rfc5806#section-6.1

### CODE REVIEW

**Comment by markjcrane** [comment]
You need to add yourself as a contributor here so that we can accept your pull request.
https://github.com/fusionpbx/open-source

**Comment by bigfishvoice** [comment]
This seems to have broken the ability to do a *72 from an end point.  Receive the following log file entry when trying to enable forwarding:
2016-08-21 13:43:44.061987 [ERR] mod_lua.cpp:203 /usr/local/freeswitch/scripts/call_forward.lua:250: unexpected symbol near char(226)

If I remove the following line from the call_forward.lua script, everything starts working again.
dial_string = dial_string .. “,sip_h_Diversion=<"..extension.."@"..domain_name..">;reason=unconditional";

**Comment by bigfishvoice** [comment]
DigiDaz figured it out on IRC.  The first double quote is not a standard ASCII quote and breaks the script.  Replace it with a stand double quote and all is well.  Please commit a fix.

**Comment by markjcrane** [comment]
Thanks for reporting the issue the double quote has been fixed.

**Pull request merged**
