### PR TITLE
Update Adminer to v4.7.5

### PR DESCRIPTION
**Pull request by powerpbx**
Could not get the current version to work with Postgres 12 so we forked the repository and created our own branch to compiled our own custom file.  It may make changes easier in the future.  

This file was compiled as multi-language.  If that is a problem or if anything else needs to be changed it should be easy to compile another file.

### CODE REVIEW

**Comment by markjcrane** [comment]
Thanks will give your version a try.

**Comment by markjcrane** [comment]
Login still failed on my server.

**Comment by powerpbx** [comment]
I presume you are referring to autologin.  That is a separate issue.  That may require some changes on the fusionpbx autologin functions.  For now you just need to press the login button.  I haven't found any documentation about it but there was a commit that prevents direct logins for security reasons.  So that might have something to do with it.

**Comment by markjcrane** [comment]
No I tried manual login and it failed. I understand how to manually login and the previous version allowed me to autologin but it wasn't consistent and didn't not always work either like this one.

**Comment by markjcrane** [comment]
Adminer login is flaky on the last couple versions.

**Comment by powerpbx** [comment]
I added a new commit which rolls back the upstream commit that I think causes the problem.  Let me know if this fixes the autologin problem.

https://github.com/powerpbx/fusionpbx/commit/54daaf214b2385385d44d08840896d072d741e31

**Comment by markjcrane** [comment]
Would be nice if you sent it as a pull request without that it won't get added to the code and likely adminer will be removed.

**Comment by markjcrane** [comment]
Never mind I'm removing adminer. In favor of more secure solutions.

**Pull request merged**
