### PR TITLE
Update {$mac}.cfg

### PR DESCRIPTION
**Pull request by micomms**
The following were changed to variables:  Account 1, 2, 3, 4, ring tones (P104, P423,P523& P623), PC Port (P231),  VLAN TAG (P51), Preference no key  (P85),  Dial now (P1085), SRTP mode (P183 P443 P543 P643),  Advanced VLAN (P24053), DST Start month, day, & hour (P20076, 77, & 78), DST end month, day, & hour (P20079, 80, & 81)

### CODE REVIEW

**Comment by markjcrane** [comment]
Will translate your text from all uppercase so I can stand looking at it.

**Comment by micomms** [comment]
:-) it's a habit I got from our dispatchers. Outside of this I'm a police officer and our dispatchers type everything into the CAD screen in caps. Helps when you're reading notes and driving.

**Comment by markjcrane** [comment]
Accepted your other pull requests which conflicted with this one. Please update this and then I will accept it.

**Comment by markjcrane** [comment]
To me uppercase is less readable because I read all uppercase rarely. However those that have to read it all the time seem to get used to it. Most websites and books use capitalization at the start of the line for names and places, and for acronyms. For this reason I think the majority of people are not used to all uppercase.

**Pull request merged**
