### PR TITLE
Update xml_cdr_delete.php

### PR DESCRIPTION
**Pull request by phoenix0984**
Fix delete recording from filesystem and database

### CODE REVIEW

**Comment by markjcrane** [comment]
Please sign up as a contributor. https://github.com/fusionpbx/open-source

**Comment by markjcrane** [comment]
Waiting on you signing up as a contributor without that cannot accept changes. I'll give you to the end of 2018 then I will close the pull request or accept it if you do become a contributor officially.

**Comment by phoenix0984** [comment]
Hi Mark, thought I already signed the contributors license agreement. I sent an email to open-source on 12/04. 
If there's anything else I need to commit, please let me know.

**Comment by phoenix0984** [comment]
Thanks, totally overlooked that part :/
Anyways, pull request created. Very merry Christmas everyone!

**Comment by markjcrane** [comment]
Thanks accepting your changes.

**Pull request merged**
