### PR TITLE
[dashboard] Don't show cc agent for missed calls

### PR DESCRIPTION
**Pull request by greenbea**

### CODE REVIEW

**Comment by markjcrane** [comment]
This has actually been accounted use the link below to search the xml cdr import code search for **missed_call** or  **and (cc_side is null or cc_side != 'agent')**
- https://github.com/fusionpbx/fusionpbx/blob/master/app/xml_cdr/resources/classes/xml_cdr.php

**Comment by greenbea** [comment]
That's for the CDR list page, not for the dashboard.

**Comment by markjcrane** [comment]
If the CDR has been imported and correctly states cc calls not as a missed call then the dashboard uses the missed_call field in the CDR table then this would already be accounted for.

**Comment by markjcrane** [comment]
The proper place to handle this is when the CDR is being imported into the database. The reason this is best is because it means all other places that need missed calls can do it by depending on the missed call field in CDR. A more efficient way to do it and centralizes the code that determines what is a missed call.

**Comment by greenbea** [comment]
You have a point.

**Comment by greenbea** [comment]
The CDR currently doesn't handle cc_side == agent

**Comment by markjcrane** [comment]
Addressing this in the CDR import.
https://github.com/fusionpbx/fusionpbx/commit/e3b600eaff4bc1de8efc0be1f781d8036639e08e

**Pull request closed without merging**
