### PR TITLE
 New Yealink Template Variables, New W41p Template 

### PR DESCRIPTION
**Pull request by emaktech**
Added new variables in the Yealink templates and performed some cleanup. Highlights:

** Conference **
{$yealink_conference.with_previous_call.enable}
{$yealink_conf.combine_with_one_press.enable}
{$yealink_call_appearance.conference_via_new_linekey}

** Network WiFi **
{$yealink_wifi_enable}
{$yealink_wifi_1_label}
{$yealink_wifi_1_ssid}
{$yealink_wifi_1_priority}
{$yealink_wifi_1_security_mode}
{$yealink_wifi_1_cipher_type}
{$yealink_wifi_1_password_}
{$yealink_wifi_1_eap_type}
{$yealink_wifi_1_eap_user_name}
{$yealink_wifi_1_eap_password}
{$yealink_wifi_show_scan_prompt}

** Jitter Buffer **
Added new jitter buffer variables for all supported phones. Also Added WiFi jitter buffer variables to T2x templates for phones that support WF40/WF50 dongles.

{$yealink_jib_adaptive}
{$yealink_jib_min}
{$yealink_jib_max}
{$yealink_jib_normal}

{$yealink_jib_wifi_adaptive}
{$yealink_jib_wifi_min}
{$yealink_jib_wifi_max}
{$yealink_jib_wifi_normal}

** Echo Cancellation **
{$yealink_voice_lec}
{$yealink_voice_vad}
{$yealink_voice_cng}

** NEW W41p Template **
Added new provisioning template for Yealink W41p kit which can be used to provision T41S/T42S with DECT dongle.

** W60B Codec Fixes **
Updated Yealink W60B default codec order to prefer G.722 instead of PCMU.

** Consistency improvements **
Improved consistency across all templates in various areas and other minor changes.

### CODE REVIEW

**Comment by markjcrane** [comment]
yealink_jib_adaptive not a fan of this type of name jib should be jitter_buffer

**Comment by markjcrane** [comment]
$yealink_conference.with_previous_call.enable no sure how this is supposed to work.

**Comment by markjcrane** [comment]
You will need to call me during working hours to go over the changes. I will not accept big sweeping changes automatically as ultimately people will hold me responsible for something breaking.

**Comment by markjcrane** [comment]
This will add some variables and remove some existing yealink variables so the merge wasn't done carefully enough.

**Comment by emaktech** [comment]
> yealink_jib_adaptive not a fan of this type of name jib should be jitter_buffer

I just followed Yealink's naming convention in their templates for this but obviously can be changed if you prefer, just let me know.

> $yealink_conference.with_previous_call.enable no sure how this is supposed to work the period is reserved for the template engines syntax.

This is fixed - good catch. I had messed up the new variable name here.

> You will need to call me during working hours to go over the changes. I will not accept big sweeping changes automatically as ultimately people will hold me responsible for something breaking. So big changes need to be carefully considered as they may work great for you and break something other people need.

Yes, makes sense. We can definitely get on a call tomorrow. In reality there are fare fewer changes than it may seem. I'm not sure why Github is highlighting identical lines as changed as they haven't. Unless I missed something really egregious, the new variables and new template and codec fix on the W60b template are the only changes in reality.

> This will add some variables and remove some existing yealink variables so the merge wasn't done carefully enough.

I went over everything again and I found two lines that were missing new variables when I merged my changes with the latest templates in the {$mac}.cfg for the T20p and T27p. Really no variables are removed - I started with the latest templates from this afternoon. The two lines in those two files have now been resolved.

**Comment by emaktech** [comment]
Closing pull request and will recreate.

**Comment by markjcrane** [comment]
I will have more time next week after the training. A call would be great to go over it then.

**Pull request closed without merging**
