### PR TITLE
BugFix-Default-MOH

### PR DESCRIPTION
**Pull request by mafoo**
Added basic searching for moh

added basic searching for the default moh directory
added app_defaults so moh is configured/repairable with app_defaults
changed to use PROJECT_ROOT
changed template replacement to be encased in comment so xml will
validate
changed to use preg_replace so leading spaces and tabs can be stripped
(to output clean xml)
local_stream_conf dos2unixed
made default search consistent (they should all be music/default or
music not a mixture)

### CODE REVIEW

**Comment by markjcrane** [comment]
Great changes good job large improvement over what was there.

**Comment by markjcrane** [comment]
Missed the forward slash on the beginning and last part of the pattern without it the xml file is empty.
$file_contents = preg_replace("/music\/default/", $default_moh_prefix, $file_contents);
$file_contents = preg_replace("/[\t ]*(?:)?/", $xml, $file_contents);

**Comment by markjcrane** [comment]
I committed a fix for it.

**Comment by mafoo** [comment]
Oups thank you, i keep forgetting the '/' inside preg_replace as i am used to using them as the string delimiter under perl

**Pull request merged**
