### PR TITLE
Enhance-Warn if posted data to big

### PR DESCRIPTION
**Pull request by mafoo**
check if the posted data exceeds php's configured maximum
- [x] Tested on Debian 8.5 VM

### CODE REVIEW

**Comment by markjcrane** [comment]
"The lowest limit of any related setting supersedes a higher setting:"
    post_max_size, upload_max_filesize, and memory_limit
I usually update upload_max_filesize. I'm concerned about the interaction between the multiple settings.

**Comment by mafoo** [comment]
Ahh! would you like me to do some more checking and warn which of any of the three is to low?

**Comment by markjcrane** [comment]
Maybe be good to have the install increase the size automatically in the php.ini file.

**Comment by mafoo** [comment]
Pushed update that now checks the three suggested values
- [x] re-Tested on Debian 8.5 VM

**Comment by markjcrane** [comment]
Since size is added to the php.ini by default I think that is sufficient.

**Pull request closed without merging**
