### PR TITLE
Grandstream Fix Logic for outbound proxy and secondary servers

### PR DESCRIPTION
**Pull request by demonspork**
There was an illogical if/else statement that the "else" condition would always set a null value, so it didn't really matter. Re-wrote it to properly filter if the transport is set to dns srv and not affix the SIP Port to the server address.

### CODE REVIEW

**Comment by markjcrane** [comment]
Currently this commit removes grandstream_ipv_mode possible other settings affected to.

**Comment by chansizzle** [comment]
@demonspork can you look through your commit and adjust to this commit? https://github.com/fusionpbx/fusionpbx/pull/5934

P1415 has been updated from hard coded to be variablized.

**Comment by demonspork** [comment]
That should do it. I also found a few examples of the variable that weren't originally updated to use the grandstream_ipv_mode variable.

**Review by chansizzle — APPROVED** [review]
looks good to me. thanks!

**Pull request merged**
