### PR TITLE
Small fixes for RU translation strings

### PR DESCRIPTION
**Pull request by Pro-pra**

### CODE REVIEW

**Comment by markjcrane** [comment]
If you look at the changes on this commit some of them are exchanging Russian for English. Please correct the problems with the translation.

**Comment by markjcrane** [comment]
This commit improves some Russian and then changes some from Russian to English.

**Comment by Pro-pra** [comment]
yes, I think that it will be more understandable than Russian translation

**Comment by markjcrane** [comment]
Can you come up with an actual Russian Translation that is intuitive? Just seems odd to replace Russian with English for the translation.

**Comment by markjcrane** [comment]
Rejecting this because its replacing Russian with English for Russian translation just doesn't seem right. I will gladly accept Russian translations.

**Comment by Pro-pra** [comment]
Many Russians do not like translated programs, because the translator translates incorrectly, sometimes the English name is more understandable.

**Comment by markjcrane** [comment]
But with that logic they might as well use the full English translation.

**Comment by Pro-pra** [comment]
Yes, its use full english translation. precisely because the translation is done poorly and it would be better to leave the part in English

**Comment by markjcrane** [comment]
Just seems goofy to create a translation that is a mix.

**Comment by Pro-pra** [comment]
Normal way. see many other translation in other programm. 
IP telephony is a rather complex topic for translation. Terminology is based on English initially.

**Pull request closed without merging**
