### PR TITLE
nl-nl items (complete) including core & default theme

### PR DESCRIPTION
**Pull request by noci2012**
If items are missing the pleas tell were other strings can be found.

### CODE REVIEW

**Comment by noci2012** [comment]
@markjcrane 
Is there a problem with this changeset?...

**Comment by noci2012** [comment]
Well most work has been undone so i give up.

**Comment by noci2012** [comment]
given up

**Comment by markjcrane** [comment]
I haven't given up. I can't translate this but I can help recover from the frustration. I used a tool to manually compare many of the files and copy over just your changes. If you email support@fusionpbx.com I can compress it and send it over to you for you to base a new pull request on it or I can commit it on your behalf with our name in the commit message. But I will only do this with your permission. Please let me know what you would like to do.

**Pull request closed without merging**
