### PR TITLE
Fix follow me caller ID query and variable 

### PR DESCRIPTION
**Pull request by FozzyGo4**
I found the wrong table was used in the query to get caller ID from follow me table as well as the incorrect variable used.

Also incorrect syntax used for the set called ID query further down.

### CODE REVIEW

**Comment by FozzyGo4** [comment]
Sorry for the double commits. This is my first time.

**Comment by markjcrane** [comment]
Pull requests should be one topic that is changed per pull request. This pull request has multiple different things. Not just fixing caller id in follow me.

**Comment by markjcrane** [comment]
For example adding South Africa to outbound routes select list should be its own pull request.

**Comment by FozzyGo4** [comment]
So sorry markjcrane. I am brand new at Githup and not to sure yet of how it all works.

Should I perhaps delete these commits and do them separately? Not sure why it added all the above commits to the fix proposal commit.

**Comment by FozzyGo4** [comment]
Closing and resubmit clean commit.

**Pull request closed without merging**
