### PR TITLE
Fix Mysql/MariaDB installation 1/2 [4.5]

### PR DESCRIPTION
**Pull request by daniel-lucio**
You commented out this line preventing the creation of all DB scheme

I really hope this was a mistake and not a strategy to discourage mysql/mariadb use.

### CODE REVIEW

**Comment by markjcrane** [comment]
If I remember right it broke other things. I haven't accepted the pull request yet because I need to see what risks the change carries.

**Comment by daniel-lucio** [comment]
So far the only back draw I have found is that music on hold is not filled (table empty). But running for a second time the upgrade scheme script populates it without error.

**Comment by devorel** [comment]
Failed to install
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fusionpbx.v_databases' doesn't exist

**Comment by devorel** [comment]
i cant install the db! 
i use i Mysql/MariaDB

**Comment by markjcrane** [comment]
Accepted this original pull request submitted by someone else.

**Comment by markjcrane** [comment]
So the change is Accepted but recommend using PostgreSQL as it is the official supported database for FusionPBX.

**Pull request closed without merging**
