### PR TITLE
BLF Presence added for Voicemail Boxes

### PR DESCRIPTION
**Pull request by tony1661**
This PR adds the ability to program BLF buttons to monitor the status of a voicemail box.

It does this by adding the _voicemail_ prefix to a BLF key. Similar to how a Call Flow uses _flow_ or how a Parking Slow uses _park_.

For example, monitoring a voicemail box 1234 you would program the BLF to be _voicemail+1234_.

### CODE REVIEW

**Comment by markjcrane** [comment]
Will likely be changing the prefix.

**Comment by johnnyq** [comment]
Nice work @tony1661 however when programmed on the phone the LED lights up when a voicemail is present but when you hit the button for the BLF key programmed it does not connect to the voicemail box. Will this feature become available at a later date?
Thank you for adding this.

**Comment by tony1661** [comment]
hi @johnnyq thanks!

That feature should already be there. It requires the dialplan to be updated. You can either execute **App Defaults** or modify it manually.

To modify it manually, go to **Dialplan > Dialplan Manager**

Search for **vmain**

The second section will have a _condition_ with a _destination_ number of: ``^(vmain$|^\*4000$|^\*98)(\d{2,12})$``

Change that to: `^(vmain$|^\*4000$|^\*98|voicemail\+)(\d{2,12})$`

Dialplan - FusionPBX

**Comment by johnnyq** [comment]
@tony1661 Thank you that did the trick! I deleted all the vmain dialplans for all the domains and then ran App Defaults as suggested.

The Voicemail feature works wonders

**Comment by tcreek** [comment]
So we literally only need to add a BLF key with  "voicemail+<extension>" to get this functioning (plus changing the vmain)?  I am trying that now, but getting nothing. Even pressing the key is like pressing *4000 or *98 only. Even putting in *98<extension? does the same thing. 

mcrane mentioned something about making changes in lua.conf.xml
I uncommented the following lines in /var/www/fusionpbx/resources/templates/conf/autoload_configs/lua.conf.xml

<param name="startup-script" value="blf_subscribe.lua voicemail"/>
<param name="startup-script" value="app/voicemail/resources/scripts/mwi_subscribe.lua"/>

No change in getting a BLF for voicemail box

**Comment by tcreek** [comment]
> yeah same here it stopped working for us too. Let me know if you come up with a resolution, ill do the same

So after some update, it stopped altogether?

**Comment by johnnyq** [comment]
yes not sure what update caused it, i had it configured on my polycom vvx311 phone.

**Comment by johnnyq** [comment]
see this link
[https://www.pbxforums.com/threads/shared-voicemail.996/page-2](https://www.pbxforums.com/threads/shared-voicemail.996/page-2)

**Comment by tony1661** [comment]
hi @johnnyq and @tcreek 

As you mentioned, for this to work you need the following in your lua.conf.xml:

```
<param name="startup-script" value="blf_subscribe.lua voicemail"/>
```

The **Dialplan Manager** portion is only used for when you actually press the button.

Have you tried restarting freeswitch after you add that line?

**Comment by johnnyq** [comment]
@tony1661 I did not realize we had to edit  /var/www/fusionpbx/resources/templates/conf/autoload_configs/lua.conf.xml and restart freeswitch Ill give that a shot tonight thanks for the input

**Comment by tony1661** [comment]
@johnnyq sorry, I've been meaning to update the documentation. I'll get a round to it soon though.

Either way, let me know how that goes 👍🏻

**Comment by tcreek** [comment]
> hi @johnnyq and @tcreek
> 
> As you mentioned, for this to work you need the following in your lua.conf.xml:
> 
> ```
> <param name="startup-script" value="blf_subscribe.lua voicemail"/>
> ```
> 
> The **Dialplan Manager** portion is only used for when you actually press the button.

Yes, but as mentioned, the button acts if you have only pressed just *98 or *4000 instead of including the extension number. Is that correct or not?


> 
> Have you tried restarting freeswitch after you add that line?

Rebooted the whole server. Or should just a special restart of FreeSwitch be done?
> 
> Edit: Can you uncomment `-- log.debug(event:serialize())` from blf_notify.lua and post your logs?

Do you mean append to ?

Like this? 
\<param name="startup-script" value="blf_subscribe.lua voicemail"/\> -- log.debug(event:serialize())

or

\<param name="startup-script" value="blf_subscribe.lua voicemail -- log.debug(event:serialize())"/\>

**Comment by tony1661** [comment]
> Yes, but as mentioned, the button acts if you have only pressed just *98 or *4000 instead of including the extension number. Is that correct or not?

They are very similar but a bit different. If you dial *98 or *4000, it will ask you for the extension, then the password. If you dial ***981234** (assuming 1234 is your mailbox) it will only ask for your password. 

Setting your BLF to **voicemail+1234** should bring you directly to the password prompt. Is that the case on your system?



> Rebooted the whole server. Or should just a special restart of FreeSwitch be done?

Reboot just the freeswitch service.

> Do you mean append to ?
> 
> Like this? <param name="startup-script" value="blf_subscribe.lua voicemail"/> -- log.debug(event:serialize())
> 
> or
> 
> <param name="startup-script" value="blf_subscribe.lua voicemail -- log.debug(event:serialize())"/>

This is only actually needed if the light is not coming on. In your example you added it to the XML but it should actually just be uncommented from `/usr/share/freeswitch/scripts/app/voicemail/resources/functions/blf_notify.lua`


--

Just as a FYI, the changes made have two parts to it. There is the Dialplan side and the BLF Subscription side.

The Dialplan is what makes it so that the button is press-able (is that a word??).

The BLF Subscription side is handled by the LUA code. That is what updates that phone's light when a message has been left.

Which part is not working for you?

**Comment by tcreek** [comment]
Both are not functioning

**Comment by tony1661** [comment]
@tcreek does dialing *981234 work?

**Comment by tcreek** [comment]
I did a fresh install on Debian 11. The *981234 and voicemail+1234 is dialing to the extension's voicemail.

I have two of those BLF buttons set up on a Yealink expansion board. For *981234, the light is a constant green even when a new voicemail arrives. 

For the voicemail+1234, there is no green light. Also the icon for that extension comes up as if the extension is not available. However, when a new voicemail comes in, the light turns red, and the available icon still shows not available extension.

image


I would say something with the update.upgrade is broken,

**Comment by tony1661** [comment]
@tcreek yea `*981234` as a BLF wont work. Only `voicemail+1234`. I wrote it to sorta follow the same format as park, call flows dnd etc.

If you look at the **Files Changed** tab of this PR, you will see what modifications I implemented. You are probably spot on that the updater doesn't include the lua script modifications.

The updater _should_ however fix the DialPlan Manager part.

Let me know how that goes! 👍🏻

**Comment by johnnyq** [comment]
@tcreek 
I made the changes to  /var/www/fusionpbx/resources/templates/conf/autoload_configs/lua.conf.xml

I created a BLF key voicemail+800
I leave a voicemail. 
The BLF key lights up red indicating I have a message
Press BLF Key button does not dial into voicemail soft buttons exit and end call come up but nothing
Listen to voicemail through web interface the BLF key light goes out as there are new messages
Press the BLF key and it dials the voicemail as normal
Its real weird if I have a new voicemail and the light is lit I can't access it
if I play the voicemail from the web ui the button light goes off and it dials the voicemail as normal.

**Comment by tcreek** [comment]
> @tcreek yea `*981234` as a BLF wont work. Only `voicemail+1234`. I wrote it to sorta follow the same format as park, call flows dnd etc.
> 
> If you look at the **Files Changed** tab of this PR, you will see what modifications I implemented. You are probably spot on that the updater doesn't include the lua script modifications.
> 
> The updater _should_ however fix the DialPlan Manager part.
> 
> Let me know how that goes! 👍🏻

It seems the first two files listed did not have the changes in them.

**Comment by tony1661** [comment]
@tcreek did that fix the issue for you?

It'll be good for future users who see this thread to know they may need to manually update the files in upgrading. I will mention to @markjcrane about maybe adding notes in the upgrade to version 5 that these files need to be manually modified.

**Comment by tcreek** [comment]
Yes, it is functioning now. 

On this update, the green light still stays off, and red comes on when there is a new voicemail.

The icon is also still showing not available extension. I would surmise that is the reason for the lack of green light.

**Comment by tony1661** [comment]
@tcreek It will depend on your model of phone. The BLF can only be on or off. The phone decides what on and off looks like.

**Comment by tcreek** [comment]
That is not the issue. A Yealink telephone will report if the extension is available or not. In the case *981234, the Yealink is showing the green light, and the icon for an available extension. This is the same case with Asterisk, or FusionPBX. 

When we set the BLF to voicemail+1234, then that is what changes. Shows extension is not available by lack of green LED, and extension not available icon.

**Comment by tony1661** [comment]
*981234 on a BLF shouldn't work. It shouldn't change when a voicemail is left

**Comment by tcreek** [comment]
Yes, I know, and I am aware of that, but explaining extension presence. Using *981234 is showing an extension as present, but voicemail+1234 is not showing an extension as present.

**Pull request merged**
