### PR TITLE
Windows ODBC driver and DSN are not required

### PR DESCRIPTION
**Pull request by sergey-mz**
You are using PDO to access database. It doesn't need ODBC driver unless you want to use php_pdo_odbc extension.

### CODE REVIEW

**Comment by moteus** [comment]
FS natively supports only SQLite on Windows.
So to be able access to Fusion database from Lua scripts
need ODBC DSN. In other case FS will not works.

**Comment by sergey-mz** [comment]
Where do you set ODBC DSN name for lua scripts to use?

**Comment by moteus** [comment]
dsn name should be same as database name.
and `freeswitch` for FS database if you want to use it for FS core database.

**Comment by markjcrane** [comment]
Advanced -> Databases and set type to ODBC. Advanced -> Upgrade -> Defaults to rewrite the config.sh

**Pull request closed without merging**
