### PR TITLE
Fix programmable keys in Aastra provisioning template

### PR DESCRIPTION
**Pull request by powerpbx**
Tested on Aastra 57i

### CODE REVIEW

**Comment by markjcrane** [comment]
Won't accept changes unless signing the contributor license agreement.

**Comment by powerpbx** [comment]
I followed the instructions and sent the information a few weeks ago.

**Comment by markjcrane** [comment]
Under a different github user account? I don't see your pull request.
Or your username listed here https://github.com/fusionpbx/open-source/tree/master/contributors

**Comment by markjcrane** [comment]
Maybe your pull request wasn't in the right directory?

**Comment by powerpbx** [comment]
I do not understand what you are saying.  I submitted a pull request and signed your contributor license agreement.  I don't see what else it is I am supposed to do.

**Comment by markjcrane** [comment]
Do you see yourself in this list?
https://github.com/fusionpbx/open-source/tree/master/contributors

**Comment by powerpbx** [comment]
No, am I supposed to add myself?  I though I was supposed to send you an email and then you do that.  I sent you an email twice now.

**Comment by markjcrane** [comment]
Yes you are supposed to add yourself to the list with a pull request into the contributors directory. The email is secondary.

**Comment by markjcrane** [comment]
Accepting your pull request.

**Pull request merged**
