### PR TITLE
Make debugging easier

### PR DESCRIPTION
**Pull request by DigiDaz**
Change access denied to more informative message to assist debugging

### CODE REVIEW

**Comment by markjcrane** [comment]
I just noticed you are not in https://github.com/fusionpbx/open-source/tree/master/contributors please complete as others have done. Once you have I will accept your changes. This was an oversight maybe assumed you had already done it.

**Comment by moteus** [comment]
Does it reduce security?

**Comment by DigiDaz** [comment]
moteus, it just changes the two access denied messages to something a little more informative. Its mainly to help people on IRC who are seeing this message. I don't see any security issue.

**Comment by moteus** [comment]
I mean that attacker then will know that there turn on digest auth.
I think better just return 404 in all cases and not return 200 with text description.

**Comment by DigiDaz** [comment]
Moteus,

I would guess if he is savvy enough to be making such an attack, he would also be having the sense to view the source code and craft the attack accordingly anyway.

**Comment by moteus** [comment]
If server will return 404 attacke will know even if there provision exists.

**Comment by markjcrane** [comment]
Its not descriptive specifically to prevent telling hackers useful information.

**Pull request closed without merging**
