### PR TITLE
Fix IVR when using custom recordings

### PR DESCRIPTION
**Pull request by daniel-lucio**
if the filename is not an absolute path, freeswitch will look the file in the sounddir directory. This makes sure the file gets the absolute path.

### CODE REVIEW

**Comment by markjcrane** [comment]
Relative paths were used by design and are working.

**Comment by daniel-lucio** [comment]
Thats my big concern, the lua script was not able to find the recording using relative path. This means there is a condition that it is failing (i bet not always), what file or piece of code does that decision? I will take a look and find if there is a wrong condition there.

**Comment by markjcrane** [comment]
Well you failed to mention details like version of fusionpbx and xml handler or ivr_menu.lua.

**Comment by daniel-lucio** [comment]
4.2.1, it was an installation not done by me. After looking, it seems it was using xml handler, I didnt find any ivr_menu.lua reference.

**Pull request closed without merging**
