### PR TITLE
Fix Yealink Expansion Modules in Device Profiles

### PR DESCRIPTION
**Pull request by konradSC**
The 'if' statements need to reference v_device_profile_keys.profile_key_vendor instead of device_key_vendor which is in a different table.

### CODE REVIEW

**Comment by markjcrane** [comment]
Good catch accepting your pull request.

**Comment by markjcrane** [comment]
This actually seems to  break the yealink expansion modules when using Device Profiles.

**Comment by markjcrane** [comment]
You save the Expansion and it get turned into Line instead of Expansion.

**Comment by markjcrane** [comment]
Looked like you were on the right track just may have missed changing Yealink see the commit for details.
https://github.com/fusionpbx/fusionpbx/commit/90dc96d1340ab9c9f6ed621005163615378e9138

**Comment by konradSC** [comment]
Yep. Looks like I missed one. Thanks!!

**Pull request merged**
