### PR TITLE
Created Template file for HT801

### PR DESCRIPTION
**Pull request by kshah37**
We are at our company, SmartIP, using grand stream ATA ht801. But I did not find template for ht801. So I created template for it.

### CODE REVIEW

**Comment by Scuzz12** [comment]
The HT802 template is a combined template for both HT801 and HT802, When configured under devices and provisioned, The registrations tab will show the proper agent for the device configured.

**Comment by demonspork** [comment]
This would be a good use for something related to #5847 - see the discussion there

**Comment by markjcrane** [comment]
> This would be a good use for something related to #5847 - see the discussion there

It’s an interesting approach but expect there us a better way than of the current suggested ideas.

**Comment by kshah37** [comment]
> The HT802 template is a combined template for both HT801 and HT802, When configured under devices and provisioned, The registrations tab will show the proper agent for the device configured.

hi, Can we try to change the folder name "HT80X" or HT801/802 instead of just "HT802". So everyone can know that this is not just for HT802?

**Comment by tony1661** [comment]
I agree with @kshah37 . It currently looks like there is only support for the HT802.

**Comment by markjcrane** [comment]
I also agree with @tony1661 and @kshah37. Please sign the contributor agreement here and your pull request will be accepted.
- https://github.com/fusionpbx/open-source

**Comment by kshah37** [comment]
> Please sign the contributor agreement here and your pull request will be accepted.
> 
> * https://github.com/fusionpbx/open-source

hi Mrak, I signed the agreement already. Please check it.

**Comment by markjcrane** [comment]
I looked and can't find the pull request for user kshah37

**Pull request merged**
