### PR TITLE
Create mailer-app-$call_uuid.log instead mailer-app.log

### PR DESCRIPTION
**Pull request by daniel-lucio**
This for sure will make easier life when debugging.

### CODE REVIEW

**Comment by markjcrane** [comment]
Though this could be useful within a short period of time the logs would be stacking up in the tmp directory.

**Comment by daniel-lucio** [comment]
Yes, you are right. Let me recode to have a default setting for that.

**Comment by daniel-lucio** [comment]
Check it

**Comment by markjcrane** [comment]
Closing incompatible pull request.

**Pull request closed without merging**
