### PR TITLE
Enhance [master] - provision aastra 9133i

### PR DESCRIPTION
**Pull request by mafoo**
provision aastra 9133i based phones (480i 480i CT, 9112i, 9133i)
leverage smarty include to common parts
have device_edit ignore 'include' folders

### CODE REVIEW

**Comment by markjcrane** [comment]
To get faster approval in the future. Make changes to rewrite rules in its own commit. Changes to aastra provisioning in its own commit and so on. This makes less of a risk to apply.

**Comment by mafoo** [comment]
Updated to remove .htaccess spacing update

**Comment by mafoo** [comment]
Would you like me to make a more generalized pass and add aastra_time_zone and convert the existing templates to also leverage the includes?

**Comment by markjcrane** [comment]
I don't understand the reason for the change to  app/devices/device_edit.php other than that I'm fine with the changes.

**Comment by markjcrane** [comment]
My main concern with what was left was the changes to app/devices/device_edit.php other than that I'm fine with the changes and so I accepted the pull request and backed out the changes to device_edit.php if you want to have them added submit a new pull request explaining reasons for the changes.

**Pull request merged**
