### PR TITLE
Device edit mac input filter

### PR DESCRIPTION
**Pull request by minotaur01**
Added key press filter for invalid characters
Added automatic striping of invalid character on paste

### CODE REVIEW

**Comment by DigiDaz** [comment]
I may be wrong but I believe you should be able to enter the device mac address with colons?

If this is the case, won't:

echo "	<input class='formfld' type='text' name='device_mac_address' id='device_mac_address' maxlength='12' value=\"$device_mac_address\"/>\n";

prevent that?
Should maxlength at least not equal 17?

**Comment by minotaur01** [comment]
That is true, max length 12 would prevent that, but do the mac not get saved without the colons and dashes anyway?

That's why there is a javascript at the bottom that removes all colons, dashes and white space on paste, to normalize the mac, and now that i think about it it should also remove all other non valid characters and  lower case it.

**Comment by DigiDaz** [comment]
I didn't realise it was javascript, I thought it was cleaned up after it was submitted

**Comment by markjcrane** [comment]
I don't like it being cleaned up by javascript should be done server side. 

Also this is not always going to be a mac address so might be renamed to device id as some soft phones do not use a mac address.

**Comment by markjcrane** [comment]
It is stripped on the server side with $device_mac_address = strtolower(preg_replace('#[^a-fA-F0-9./]#', '', $device_mac_address)); I don't like it being done by javascript as it can easily be bypassed. Also because this doesn't have to be a real mac address for soft phones and for hot desking. Closing the pull request.

**Comment by minotaur01** [comment]
K, but it's all the provisioning code based on a mac? And since you are all ready filtering it on the server based on the mac format i didn't think it would be a issue to do it right away on the client side. 
Also the next step to this was to have the client side automatically filter out keys and templates for the specific vendor based on the mac!

**Pull request closed without merging**
