### PR TITLE
[4.4] Make intercept feature more fault tolerant

### PR DESCRIPTION
**Pull request by daniel-lucio**
Same as #6788

### CODE REVIEW

**Comment by markjcrane** [comment]
Anyone still using 4.4 is irresponsible and putting their customers at risk for not upgrading. This branch is not maintained for vulnerabilities. I will be removing this branch. To discourage those still using it.

**Comment by daniel-lucio** [comment]
It is more irresponsible to neglect the security patches; instead, you choose to call out your users.

You should be grateful that when someone finds an issue, he/she takes the time to verify if the same patch applies to all the branches.

**Comment by demonspork** [comment]
He's trying to say that 4.4 is an abandoned, unsupported, not recommended version of this product. Every software developer has to draw a line on support and patches for old versions and he has clearly, multiple times, drawn that line in the sand for you specifically.

There is a clear upgrade path to the supported versions and branches with no loss of function.

**Comment by markjcrane** [comment]
When Ubuntu LTS (long term support) is five years old its end of life.  Same for some versions of Debian that get long term support. FusionPBX 4.4 released 5 April 2018 and is 5.5 years old. So it is end of life even by that point of view.

FusionPBX 4.4 is end of life. For those that don't upgrade you are putting your customers at RISK. There are multiple known vulnerabilities in it. Many that will likely be missed by anyone who tries to secure it.  From a different point of view anyone still on 4.4 is missing 5.5 years of development that makes you less competitive than those using the latest release version.

**Pull request closed without merging**
