### PR TITLE
Escene provision

### PR DESCRIPTION
**Pull request by moteus**

### CODE REVIEW

**Comment by screwloose83** [comment]
How can i add this to my current setup?

**Comment by moteus** [comment]
I think I can update it in Wensday

**Comment by moteus** [comment]
Update to current master.
@screwloose83 If you on current master and **you have no local changes** you can do from your fusion dir
```
git remote add moteus https://github.com/moteus/fusionpbx
git fetch moteus
git checkout moteus/escene_provision -b escene_provision
```
To switch back to your branch you can do
```
git checkout master
```

**Comment by screwloose83** [comment]
Cool thanks. I had to do a menu reset after doing this. It made the top menu disappear.

What format do you use in the provisioning URL on the es320?

**Comment by moteus** [comment]
URL just `http://fusionpbx.domain.local/fusionpbx/app/provision`

**Comment by screwloose83** [comment]
That’s what I had in. This is what I get in the access log. They are all getting 404’s maybe I missed something.

[04/May/2016:22:44:06 +1000] "GET /app/provision/Public.xml HTTP/1.1" 404 222 "http:// " "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
[04/May/2016:22:44:07 +1000] "GET /app/provision/sys_ES320NV3.xml HTTP/1.1" 404 228 "http:// " "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
[04/May/2016:22:44:07 +1000] "GET /app/provision/00268b0100c8.xml HTTP/1.1" 404 228 "http:// " "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
[04/May/2016:22:44:08 +1000] "GET /app/provision/1011_Phonebook.xml HTTP/1.1" 404 230 "http:// " "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
[04/May/2016:22:44:08 +1000] "GET /app/provision/Extern.xml HTTP/1.1" 404 222 "http:// " "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
[04/May/2016:22:44:08 +1000] "GET /app/provision/1011_Extern.xml HTTP/1.1" 404 227 "http:// " "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
[04/May/2016:22:44:09 +1000] "GET /app/provision/Enterprise_Phonebook.xml HTTP/1.1" 404 236 "http:// " "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
[04/May/2016:22:44:10 +1000] "GET /app/provision/FD000320.cfg HTTP/1.1" 404 224 "http:// " "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
[04/May/2016:22:44:10 +1000] "GET /app/provision/KD000320.cfg HTTP/1.1" 404 224 "http:// " "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"

**Comment by moteus** [comment]
You need turn on provision in Fusion.
you should be able see config in browser when you type url like
`http://fusionpbx.domain.local/fusionpbx/app/provision/<mac>.xml`
or 
`http://fusionpbx.domain.local/app/provision/<mac>.xml`

PS. Better discuss such thing on irc channel.

**Pull request merged**
